"""Initial migration

Revision ID: 024794d74175
Revises: 
Create Date: 2019-07-15 23:54:39.219612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024794d74175'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=False),
    sa.Column('last_name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_user_has_t_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_user_id', sa.Integer(), nullable=True),
    sa.Column('t_group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['t_group_id'], ['t_group.id'], ),
    sa.ForeignKeyConstraint(['t_user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_user_has_t_group')
    op.drop_table('t_user')
    op.drop_table('t_group')
    # ### end Alembic commands ###
