"""empty message

Revision ID: 058296f2429d
Revises: 82364747a09a
Create Date: 2019-07-16 21:04:41.358467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '058296f2429d'
down_revision = '82364747a09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('t_user_has_t_group_ibfk_1', 't_user_has_t_group', type_='foreignkey')
    op.drop_column('t_user_has_t_group', 'invited_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user_has_t_group', sa.Column('invited_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('t_user_has_t_group_ibfk_1', 't_user_has_t_group', 't_user', ['invited_by'], ['id'])
    # ### end Alembic commands ###
