"""Add is_owner column

Revision ID: 3ed4073f2510
Revises: 058296f2429d
Create Date: 2019-07-16 21:06:48.369851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed4073f2510'
down_revision = '058296f2429d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user_has_t_group', sa.Column('is_owner', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user_has_t_group', 'is_owner')
    # ### end Alembic commands ###
