"""Add nullable to group and user in item table

Revision ID: 72c23157b61f
Revises: 79e11b19019e
Create Date: 2019-07-17 11:00:36.746261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72c23157b61f'
down_revision = '79e11b19019e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_item', 't_group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('t_item', 't_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_item', 't_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('t_item', 't_group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
