"""Add last_name from t_user

Revision ID: 95857e3d0105
Revises: eef1c75f1937
Create Date: 2019-07-10 09:13:34.675217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95857e3d0105'
down_revision = 'eef1c75f1937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('last_name', sa.String(length=45), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'last_name')
    # ### end Alembic commands ###
