"""Add item and relationships

Revision ID: 9e1b5c2ac7af
Revises: 2d2b4c8ff89a
Create Date: 2019-07-17 10:28:39.389534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1b5c2ac7af'
down_revision = '2d2b4c8ff89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_group_has_t_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_group_id', sa.Integer(), nullable=True),
    sa.Column('t_item_id', sa.Integer(), nullable=True),
    sa.Column('t_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cleared', sa.Boolean(), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['t_group_id'], ['t_group.id'], ),
    sa.ForeignKeyConstraint(['t_item_id'], ['t_item.id'], ),
    sa.ForeignKeyConstraint(['t_user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_group_has_t_item')
    op.drop_table('t_item')
    # ### end Alembic commands ###
