"""Add nullable False to t_user columns

Revision ID: a0c57f8da6a6
Revises: 3be9c9eabbe7
Create Date: 2019-07-09 19:16:03.007147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0c57f8da6a6'
down_revision = '3be9c9eabbe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('t_user', 'email',
               existing_type=mysql.VARCHAR(collation='latin1_general_cs', length=255),
               nullable=False)
    op.alter_column('t_user', 'first_name',
               existing_type=mysql.VARCHAR(collation='latin1_general_cs', length=45),
               nullable=False)
    op.alter_column('t_user', 'last_name',
               existing_type=mysql.VARCHAR(collation='latin1_general_cs', length=45),
               nullable=False)
    op.alter_column('t_user', 'password',
               existing_type=mysql.VARCHAR(collation='latin1_general_cs', length=45),
               nullable=False)
    op.alter_column('t_user', 'username',
               existing_type=mysql.VARCHAR(collation='latin1_general_cs', length=45),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_user', 'username',
               existing_type=mysql.VARCHAR(collation='latin1_general_cs', length=45),
               nullable=True)
    op.alter_column('t_user', 'password',
               existing_type=mysql.VARCHAR(collation='latin1_general_cs', length=45),
               nullable=True)
    op.alter_column('t_user', 'last_name',
               existing_type=mysql.VARCHAR(collation='latin1_general_cs', length=45),
               nullable=True)
    op.alter_column('t_user', 'first_name',
               existing_type=mysql.VARCHAR(collation='latin1_general_cs', length=45),
               nullable=True)
    op.alter_column('t_user', 'email',
               existing_type=mysql.VARCHAR(collation='latin1_general_cs', length=255),
               nullable=True)
    op.alter_column('t_user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
