"""Remove many to many items group

Revision ID: b80c4fe35a61
Revises: 9e1b5c2ac7af
Create Date: 2019-07-17 10:51:36.175383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b80c4fe35a61'
down_revision = '9e1b5c2ac7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_group_has_t_item')
    op.add_column('t_item', sa.Column('t_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_item', 't_group', ['t_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_item', type_='foreignkey')
    op.drop_column('t_item', 't_group_id')
    op.create_table('t_group_has_t_item',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('t_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('t_item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('t_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('cleared', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('removed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['t_group_id'], ['t_group.id'], name='t_group_has_t_item_ibfk_1'),
    sa.ForeignKeyConstraint(['t_item_id'], ['t_item.id'], name='t_group_has_t_item_ibfk_2'),
    sa.ForeignKeyConstraint(['t_user_id'], ['t_user.id'], name='t_group_has_t_item_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_general_cs',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
