"""Remove last_name from t_user

Revision ID: eef1c75f1937
Revises: a0c57f8da6a6
Create Date: 2019-07-10 08:01:15.798508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eef1c75f1937'
down_revision = 'a0c57f8da6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('last_name', mysql.VARCHAR(collation='latin1_general_cs', length=45), nullable=False))
    # ### end Alembic commands ###
